service:
  info: Customer Microservice (Development)

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9002/customer-services
    username: customer
    password: qwer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:1689/realms/dms
server:
  port: 9000